### ISSUE TITLE
Startup failure when enabling CORS

### ISSUE THREAD

**Issue by mschulz-716** [meggsimum/geoserver-docker#23]
When running

`docker run -e USE_CORS=1 -p 18080:8080 meggsimum/geoserver:2.21.1`

I get following error:

`17-Oct-2022 13:27:58.849 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
17-Oct-2022 13:27:58.850 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/geoserver] startup failed due to previous errors`

In the Tomcat localhost.log inside the container there is following information:

`17-Oct-2022 13:51:23.682 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
17-Oct-2022 13:51:24.863 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
17-Oct-2022 13:51:32.407 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [Request Logging Filter]
	java.lang.NoSuchMethodException: org.geoserver.filters.LoggingFilter.<init>()
		at java.lang.Class.getConstructor0(Class.java:3082)
		at java.lang.Class.getConstructor(Class.java:1825)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4608)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5258)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1177)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
17-Oct-2022 13:51:32.457 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
`

What could be the reason for this?

**Comment by JakobMiksch** [comment]
@mschulz-716 good observation. I can reproduce that, but I do not know the cause. It seems this problem is new since `2.21.x` 
Running the image with version `2.20.4` works for me like expected.

**Comment by JakobMiksch** [comment]
@mschulz-716 apparently the structure of the file `WEB-INF/web.xml` has changed. 
In #24 I added a quick fix that solved it locally for me. Maybe it helps you already.
